### PR TITLE
Feature/iat 143

### PR DESCRIPTION
**Pull request by bdrainer**
I am making similar changes to ap-iat based off Mark's comments yesterday.

Mark:  I looked at the docker command "HEALTHCHECK" but that doesn't appear to solve the problem of not starting an app before another app is ready.  The health check pings and flags itself as healthy or unhealthy depending.  I have not tried it but will when I get a chance.  I could be mistaken in my understanding. 

I am starting to rethink how I'm doing docker compose.  I have it plugged into the app where some gradle commands setup the docker and docker compose stuff.  Then a script (docker.sh) is used to bring up and down the compose stuff.  The compose file has all the services the app uses and **the app itself**.  Maybe this compose file should not have the app itself and instead only be the services the app needs.  This way one can develop the app locally while utilizing the services brought up by compose.

We could also have a GitHub repository which is nothing more than scripts, docker files, and compose files.  This repo is for standing up the entire AP suite of services ap-iat, ap-ims, config-server, ap-iss (search service), ap-irs (item rendering service), etc. outside the context of active development.  Whether this is needed or not I think is left to be determined.  Maybe it isn't if we expect to have a continuous delivery pipeline utilizing K8s and AWS where QA and UAT work from.

### CODE REVIEW

**Comment by millerts** [comment]
Just a note, TDS has a build only repository [TDS_Build](https://github.com/SmarterApp/TDS_Build) which we use to contain build script, docker compose files, and certain env files.  You can see our docker configuration [here](https://github.com/SmarterApp/TDS_Build/tree/master/docker/tds).  Each project has a docker configuration which you can find under `<tds project>/src/main/docker`

As for the waiting part we are leveraging the docker-compose [depends](https://docs.docker.com/compose/compose-file/#dependson) to ensure that services start up in the required order.  An example can be found [here](https://github.com/SmarterApp/TDS_Build/blob/master/docker/tds/docker-compose.yml#L37).  It makes sure all "support" services are up before starting exam.

I do not have context for the discussion, but I just happened to still be watching this repository so I saw the comment.  Just mentioning what TDS team is doing in case there is overlap.  I'm not sure how many of our team will comment/watch on non TDS projects so feel free to tag us or hit us up in the office if there are questions or overlap on what we're doing.

**Comment by malaffoon** [comment]
There is a (newer) feature in docker-compose where the depends_on can specify that the required service must not only be started but be healthy. Search for `docker-compose healthcheck` and you should see it.

**Comment by bdrainer** [comment]
Thanks @millerts  and @malaffoon 

@malaffoon - I was able to get the healthcheck to work.  The startup script that did the looping is gone.  And instead of using netcat-openbsd it is using curl.  The first thing to get this working was changing the docker-compose version from '2' to '2.1'.  An error is thrown if version '2' is used with the 'healthcheck' property.  Once I figured this out the way it works is each service is given a healthcheck where it basically pings itself or in the case of Spring Boot we hit the acuator endpoint /health.  Then any app dependent on that service should be configured as such -> "depends_on: config-server: service-healthy".  

@millerts   I wonder if depends_on is doing what you expect.  The depends_on only starts the containers in a specific order.  Our IAT app is dependent on the config-server, and IAT app is set to fail immediately if when it starts the config-server isn't available.  The containers are started in the correct order: first the config-server then IAT.  But IAT fails immediately because the config-server spring boot is still starting up (and not yet available) by the time the spring boot IAT app starts.   There is a difference between starting the docker containers and starting the inside them apps.

**Comment by malaffoon** [comment]
Yay!

**Pull request merged**
